apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-credentials-t1552-005
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-credentials-t1552-005
  template:
    metadata:
      labels:
        app: cloud-credentials-t1552-005
    spec:
      containers:
      - name: cloud-credentials-t1552-005
        image: angelrita/base-ubuntu:latest
        command:
          - /bin/sh
          - -c
        args:
        - while true; do sleep 30; done;
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          privileged: true
