apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-escape-using-runtime-socket-t1611
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-escape-using-runtime-socket-t1611
  template:
    metadata:
      labels:
        app: container-escape-using-runtime-socket-t1611
    spec:
      containers:
      - name: container-escape-using-runtime-socket-t1611
        image: angelrita/base-ubuntu:latest
        command:
          - /bin/sh
          - -c
        args:
        - while true; do sleep 30; done;
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          privileged: true
