apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-service-account-t1609
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-service-account-t1609
  template:
    metadata:
      labels:
        app: kubernetes-service-account-t1609
    spec:
      containers:
      - name: kubernetes-service-account-t1609
        image: qualysdockerhub/overlay-functional:threatqatest
        command:
          - /bin/sh
          - -c
        args:
        - while true; do sleep 30; done;
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          privileged: true
