apiVersion: apps/v1
kind: Deployment
metadata:
  name: pexec-memory-t1106
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pexec-memory-t1106
  template:
    metadata:
      labels:
        app: pexec-memory-t1106
    spec:
      containers:
      - name: pexec-memory-t1106
        image: qualysdockerhub/overlay-functional:threatqatest
        command:
          - /bin/sh
          - -c
        args:
        - while true; do sleep 30; done;
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
          privileged: true
